/*
 * CAUTION: Don't edit this file manually.  To update this file, read
 * mklbproptab.py.
 */

#ifndef UNICODE_LINEBREAKTAB_H
#define UNICODE_LINEBREAKTAB_H

/*
 * UAX#14 Line Breaking Classes.
 */

enum unicode_lbclass
{
  /*
   * Classes appear in unicode_lbpairs[][] table.
   * NOTE: Order is important.
   */

  UNICODE_LBCLASS_OP = 0,
  UNICODE_LBCLASS_CL,
  UNICODE_LBCLASS_QU,
  UNICODE_LBCLASS_GL,
  UNICODE_LBCLASS_NS,
  UNICODE_LBCLASS_EX,
  UNICODE_LBCLASS_SY,
  UNICODE_LBCLASS_IS,
  UNICODE_LBCLASS_PR,
  UNICODE_LBCLASS_PO,
  UNICODE_LBCLASS_NU,
  UNICODE_LBCLASS_AL,
  UNICODE_LBCLASS_ID,
  UNICODE_LBCLASS_IN,
  UNICODE_LBCLASS_HY,
  UNICODE_LBCLASS_BA,
  UNICODE_LBCLASS_BB,
  UNICODE_LBCLASS_B2,
  UNICODE_LBCLASS_ZW,
  UNICODE_LBCLASS_CM,
  UNICODE_LBCLASS_WJ,
  UNICODE_LBCLASS_H2,
  UNICODE_LBCLASS_H3,
  UNICODE_LBCLASS_JL,
  UNICODE_LBCLASS_JV,
  UNICODE_LBCLASS_JT,
  UNICODE_LBCLASS_SPOP,
  UNICODE_LBCLASS_CLH,
  UNICODE_LBCLASS_CLSP,
  UNICODE_LBCLASS_CLHSP,
  /* Placeholder to indicate end of ordinal classes. */
  UNICODE_LBCLASS_TABLESIZE,

  /*
   * Below from here shouldn't appear in unicode_lbpairs[][] table.
   */

  /* SPACE */
  UNICODE_LBCLASS_SP,

  /* Explicit break. */
  UNICODE_LBCLASS_BK,
  UNICODE_LBCLASS_CR,
  UNICODE_LBCLASS_LF,
  UNICODE_LBCLASS_NL,

  /*
   * Custom classes.  These should be solved to any of classes above
   * by tailor_lbclass().
   */

  UNICODE_LBCLASS_BKO,
  UNICODE_LBCLASS_IDSP,
  UNICODE_LBCLASS_NSK,
  UNICODE_LBCLASS_OPAL
};

#define UNICODE_LBCLASS_OP_DEFINED
#define UNICODE_LBCLASS_CL_DEFINED
#define UNICODE_LBCLASS_QU_DEFINED
#define UNICODE_LBCLASS_GL_DEFINED
#define UNICODE_LBCLASS_NS_DEFINED
#define UNICODE_LBCLASS_EX_DEFINED
#define UNICODE_LBCLASS_SY_DEFINED
#define UNICODE_LBCLASS_IS_DEFINED
#define UNICODE_LBCLASS_PR_DEFINED
#define UNICODE_LBCLASS_PO_DEFINED
#define UNICODE_LBCLASS_NU_DEFINED
#define UNICODE_LBCLASS_AL_DEFINED
#define UNICODE_LBCLASS_ID_DEFINED
#define UNICODE_LBCLASS_IN_DEFINED
#define UNICODE_LBCLASS_HY_DEFINED
#define UNICODE_LBCLASS_BA_DEFINED
#define UNICODE_LBCLASS_BB_DEFINED
#define UNICODE_LBCLASS_B2_DEFINED
#define UNICODE_LBCLASS_ZW_DEFINED
#define UNICODE_LBCLASS_CM_DEFINED
#define UNICODE_LBCLASS_WJ_DEFINED
#define UNICODE_LBCLASS_H2_DEFINED
#define UNICODE_LBCLASS_H3_DEFINED
#define UNICODE_LBCLASS_JL_DEFINED
#define UNICODE_LBCLASS_JV_DEFINED
#define UNICODE_LBCLASS_JT_DEFINED
#define UNICODE_LBCLASS_SPOP_DEFINED
#define UNICODE_LBCLASS_CLH_DEFINED
#define UNICODE_LBCLASS_CLSP_DEFINED
#define UNICODE_LBCLASS_CLHSP_DEFINED
#define UNICODE_LBCLASS_BKO_DEFINED
#define UNICODE_LBCLASS_IDSP_DEFINED
#define UNICODE_LBCLASS_NSK_DEFINED
#define UNICODE_LBCLASS_OPAL_DEFINED

extern struct unicode_lbprop *unicode_getprop_generic(unicode_char);
extern struct unicode_lbprop *unicode_getprop_C(unicode_char);
extern struct unicode_lbprop *unicode_getprop_G(unicode_char);
extern struct unicode_lbprop *unicode_getprop_J(unicode_char);
extern struct unicode_lbprop *unicode_getprop_K(unicode_char);

#endif /* UNICODE_LINEBREAKTAB_H */
